### ISSUE TITLE
Can't reset from inside of nested navigato

### ISSUE THREAD

**Issue by msdark** [react-community/react-navigation#1436]
### Current Behavior
Current definition of my navigators
```javascript
const AppNavigator = StackNavigator({
  Home: { screen: SigninScreen },
  Tabs: { screen: TabNavigator }, // A Tab Navigator
});

const TabScreen = TabNavigator({
  Saldos: { screen: SaldosScreen },
  Operaciones: { screen: OperacionesNavigator }, // a Stack Navigator
  Retenciones: { screen: RetencionesScreen },
  Ejecutivo: { screen: EjecutivoScreen },
});

const OpNavigator = StackNavigator(
  {
    Operaciones: { screen: OperacionesScreen },
    OperacionesDetails: { screen: OperacionesDetails },
  })
```
The app start with the `Home` screen, after user enter the login details the app redirects to the `TabNavigator` and the user is only able to navigate through that set of screens. (back button is disabled).

I add a logout button
```javascript 
const logout = NavigationActions.reset({
  index: 0,
  actions: [NavigationActions.navigate({ routeName: 'Home' })],
});

const LogoutButton = ({ dispatch }) => (
  <TouchableOpacity
    onPress={() => dispatch(logout)}
    style={{
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
    }}
  >
    <Icon
      name="log-out"
      style={{ color: 'white', marginRight: 10, marginTop: 5 }}
    />
  </TouchableOpacity>
);

LogoutButton.propTypes = {
  dispatch: PropTypes.func.isRequired,
};

export default connect()(LogoutButton);
```

But onPress the button this errors raise
> There is no route defined for key Home.
> Must be one of:
> 'Operaciones, OperacionesDetails'

That errors shows only tow possible routes. That routes belongs to the `OpNavigator` but the current active screen is `Saldos` that belongs to `TabNavigator`.

What is the correct way to setup the navigators and perform the stack reset?.

The desired stack is.
|- Home (always the first screen to be loaded)
|- LoadingScreen (used in the transition from Home to Tabs)
|-- Tabs
|---- Operaciones (is a tab that holds two other screens as a Stack Navigator)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  git+https://github.com/react-community/react-navigation.git
| react-native     |  https://github.com/exponent/react-native/archive/sdk-16.0.0.tar.gz
| node             | v7.7.2
| npm or yarn      | yarn 0.21.3 npm 4.1.2

**Comment by perscrew** [comment]
Hi ! I've the same problem with the DrawerNavigator component. When I reset the router state the drawer menu is replaced by the nested route screen.

**Comment by supportclik** [comment]
+1

**Comment by perscrew** [comment]
Hi everybody, I solved my problem with the last release v1.0.0-beta.9.

I cannot reproduce the bug.

Be carefull the navigatorOptions have been flatten, you should rewrite all your options.

**Comment by ericvicenti** [comment]
Ok I think this has been fixed

**Comment by dabit1** [comment]
It hasn't been fixed, I having this issue on v1.0.0-beta.10

**Comment by dhyegofernando** [comment]
👍  how to reset it?

**Comment by perscrew** [comment]
I agree with @dabit1 it still doesn't work with v1.0.0-beta.10 version.

**Comment by allpwrfulroot** [comment]
This has been working for me since v9. Not a full reset, but it gets me to the right tab? Some experimentation with levels of Stack/Tab navigators -> routeNames was required:
```
onPress={() => (navigation.state.index === 0 && navigation.state.routes[0].routes[0].index === 1) ?
            navigation.navigate('DrawerClose') : navigation.dispatch(
              NavigationActions.navigate({
                routeName: 'Summary',
                params: {},
                action: NavigationActions.navigate({ routeName: 'TravelTab' })
              })
            ) }
```
