### ISSUE TITLE
sub action not working in reset 

### ISSUE THREAD

**Issue by cbjs** [react-community/react-navigation#1620]
```js
  const navigateAction = NavigationActions.navigate({
        routeName: 'home',
            action: NavigationActions.navigate({
              routeName: 'message',
              params: {}
            })
          });

          const resetAction = NavigationActions.reset({
            index: 0,
            actions: [ navigateAction ]
          });

navigator.dispatch(resetAction);
```
stop at home screen.

**Comment by matthamil** [comment]
Can you provide more information about the behavior you are expecting and the behavior you are seeing?

**Comment by cbjs** [comment]
@matthamil 

```js
const RootNavigator = StackNavigator({
  home: {screen: Home, path: '/'},
  board: {screen: BoardDetail, path: '/board/:board' },
  article: {screen: PostDetail, path: '/article/:board/:id' },
  dialogue: {screen: PostDialogue, path: '/article/:board/:id/:userOne/:userTwo' },
}, {
  initialRouteName: 'home'
}

const Home = TabNavigator({
  boards: {
    screen: ScrollTabBoards,
  },
  discover: {
    screen: Discover,
  },
  message: {
    screen: Message,
  },
  profile: {
    screen: Profile
  },
}, {
  initialRouteName: 'boards',
  }
})
```

I wanna wipe the whole navigation state, and then navigate to ```message``` sub screen.
it stop at initial ```boards``` screen, sub action is not working.

 ```navigator.dispatch(navigateAction)```  is working.

**Comment by cbjs** [comment]
@matthamil 

same problem with https://github.com/react-community/react-navigation/issues/1127
i will check new version 1.0.0-beta.10

**Comment by cbjs** [comment]
1.0.0-beta.10 still not working

**Comment by emaildostrider** [comment]
Still no working for me to :(

**Comment by zmGitHub** [comment]
+1

**Comment by ZHT131** [comment]
+1

**Comment by Naiba01** [comment]
is this problem solved now?

**Comment by kelset** [comment]
Pinging OP @cbjs  since this issue is quite old and related to an old version of the lib. If no answer I'll close in 7 days. (Moreover, there are a lot of issues like this related to reset so I'd prefer to close it to lower the redundancy)

**Comment by kelset** [comment]
Hi there @cbjs ,

In an effort to cleanup this project and prioritize a bit, since this issue had no follow up since my last comment I'm going to close it.

If you are still having the issue with the latest version (especially if it's a bug report) please check the current open issues, and if you can't find a duplicate, open a new one that uses the new Issue Template to provide some more details to help us solve it.

**Comment by mbret** [comment]
Problem still here with latest version. That's a pretty annoying problem for my current app. Any news ?

**Comment by JulianKingman** [comment]
I'm having the same issue, it's being tracked here: https://github.com/react-navigation/react-navigation/issues/1715

**Comment by yashojha19** [comment]
stuck in the same problem. I can use reset action when I try to navigate from child navigator to parent navigator when I set the key as null, but when I try to go from Parent navigator to child navigator, it isn't working.
```
      this.props.navigation.dispatch(
        NavigationActions.reset({
          index: 0,
          actions: [
            NavigationActions.navigate({
              routeName: "routename", //screen from current navigator
              params: {},
              action: NavigationActions.navigate({
                routeName: "child_routename" //child navigator screen
              })
            })
          ]
        })
```
I don't understand why this is happening ? 
this.prop.navigation.navigate("child_routename")
anyone found the solution or workaround ?

**Comment by lequangdzung** [comment]
I got the same issue with version `1.0.2` :(

**Comment by brentvatne** [comment]
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!
