### ISSUE TITLE
setParams causing tab to become active

### ISSUE THREAD

**Issue by lprhodes** [react-community/react-navigation#1711]
### Current Behavior
Calling `this.props.navigation.setParams({ something: 'here' })` on a tab that's inactive caused that tab to become active.

### Expected Behavior
The active tab should not change.

Using react-native 0.44

**Comment by tamdesktop** [comment]
I got same issue

**Comment by DavoCg** [comment]
Same here, if anyone have an idea

**Comment by mnkang89** [comment]
+1

**Comment by ghuh** [comment]
+1

**Comment by tamdesktop** [comment]
@ghuh same with you, lazy load resolved my problem.

**Comment by DavoCg** [comment]
Yes but I don't want lazy: true, the solution I found it to wrap setParams around setTimeout with 0ms

**Comment by DaveCole** [comment]
+1

**Comment by DaveCole** [comment]
While the above did not work for me, I found that if I followed the setParams call (I use dispatch below) with a call to navigate the tab back to where it was in the first, place, this worked - in this case 'HomeStack' is my tab #1 and I'm setting params on tab #2:

``
this.props.navigation.dispatch(setParamsAction);
                this.props.navigation.dispatch(
                  {
                      type: 'Navigation/NAVIGATE',
                      routeName: 'HomeStack',
                      action: {
                        type: 'Navigation/NAVIGATE',
                        routeName: 'HomeStack',
                      }
                  }
                 );
``

**Comment by Tom29** [comment]
@DaveCole I've tried to dispatch two actions at the same time like this:

```
const setParamsAction1 = NavigationActions.setParams({ params: { foo: 'bar' } }, key: 'a' });
const setParamsAction2 = NavigationActions.setParams({ params: { foo: 'bar' } }, key: 'b' });
this.props.navigation.dispatch(setParamsAction1);
this.props.navigation.dispatch(setParamsAction2);
```

but didn't work

**Comment by luco** [comment]
+1 on this

**Comment by lbrdar** [comment]
+1

Any news on this, guys? Hacks above didn't help me (except for dispatching the navigate action to go back, but that is such a terrible hack I would rather not use it :/ )

@DavoCg can you please provide an example of call that worked for you?

**Comment by llaine** [comment]
+1 on this, here a snack to reproduce the issue https://snack.expo.io/HJmosSpcW

**Comment by zhouanbo** [comment]
+1 on this, wondering if it's solved yet

**Comment by wellyshen** [comment]
+1 I have the same issue

**Comment by danielcdcj** [comment]
+1 I have the same issue

**Comment by tienph4m** [comment]
I've just been doing a bit of digging into the source code, and I think I know why this happens.

https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js#L214
TabRouter will try to handle the action passed in, but when it thinks it cannot handle the action, it will let its tabs handle the action. In this case, one of the tabs is a StackRouter and its state will be updated after handling the action, thus TabRouter will update its index
https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js#L243

I'm not sure why we want this, I really can't think of any use-case where this is necessary. Removing the code from L215 to L248 will fix the issue. I'm happy to submit a pull request, but I think I need more context to give the exact answer. Does anyone know why we want to switch to the first tab that returns a new state?

**Comment by tienvpham** [comment]
I've just been doing a bit of digging into the source code, and I think I know why this happens.

https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js#L214
TabRouter will try to handle the action passed in, but when it thinks it cannot handle the action, it will let its tabs handle the action. In this case, one of the tabs is a StackRouter and its state will be updated after handling the action, thus TabRouter will update its index
https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js#L243

I'm not sure why we want this, I really can't think of any use-case where this is necessary. Removing the code from L215 to L248 will fix the issue. I'm happy to submit a pull request, but I think I need more context to give the exact answer. Does anyone know why we want to switch to the first tab that returns a new state?

**Comment by metelski** [comment]
Hi everyone. Any chance to have this thing sorted out?
I use `setParams` to update a `TabNavigator` bell icon representing notifications screen. When a new notification is received, the bell icon gets decorated with a small dot.
This bug causes an immediate, unnecessary jump to notifications screen. Please help.

**Comment by mattias800** [comment]
Still an issue in `1.0.0-beta.12`.

**Comment by zhouanbo** [comment]
It's solved in not yet merged pull request #2674

**Comment by vonovak** [comment]
#2674 was merged so this should no longer be an issue

**Comment by goinnovative** [comment]
lazy: true solved the problem for me, thank you! 👍

**Comment by ghuh** [comment]
#2674 Didn't fix the issue for us.  Here is the patch we used to fix the problem if anyone else needs it: https://github.com/react-community/react-navigation/pull/3137

**Comment by feliperaul** [comment]
We're still having this on `"react-navigation": "1.5.11"`

**Comment by brentvatne** [comment]
can someone who would like to see this issue resolved please create a new issue with a reproducible example on https://snack.expo.io or in a github repository, with a minimal amount of superfluous code? (please don't post your entire app, just a small one to reproduce the problem). thanks!
