### ISSUE TITLE
Reset action side effects when implementing #2520 goBack fix

### ISSUE THREAD

**Issue by eballeste** [react-community/react-navigation#3098]
### Current Behavior
#2520 Introduced a fix for using keys with the goBack action but in order for you to use it, you need to include the author's forked version of `react-navigation-addons`. This causes side effects with the `NavigationActions.reset` method, causing them to mount and rerender again before fully unmounting. The problem seems to be caused by the original repo of `react-navigation-addons` https://github.com/satya164/react-navigation-addons/issues/14.

### Expected Behavior
- Use of goBack with a key and a single screen animating & use of reset without the unloaded screens temporarily mounting again, triggering their lifecycle events in the process. 

- IMHO, the dependency on a forked version of `react-navigation-addons`, whose original repo is unmaintained and has it's own set of bugs, should not have been merged into this library. I went down a rabbit hole of time wasted implementing the update, me celebrating finally getting my navigation to work correctly, only to find out all of my resets now have side effects, also package.json does not reflect this dependency, I found it in the comments of the PR.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0.0-beta.21
| react-native     | 0.50.1
| node             | 7.10.0
| npm      | 4.2.0

**Comment by kelset** [comment]
Hey thanks for reporting but what you are saying is that you want to have 

> keys with the goBack action

so you decided to use his approach. And that approach has its bugs.
This library doesn't "force" you to install it to obtain that feature, so I don't see the point "blaming us" for something like this.

Instead, there are some PRs to add that feature, like this one: https://github.com/react-community/react-navigation/pull/3085

So my suggestion is that you don't use that extra forked library, but instead try out that PR, and if it works for you write a comment there that will help us test & review & merge it.

**Comment by eballeste** [comment]
You guys are pointing to that PR in every single issue you close that is related to resetting the navigation stack or going back to a certain screen without seeing all the screens animate as **the** fix for it.

By keys, I meant routeNames, going back to a certain screening by specifying it's routeName, with a single animation from current screen to the target screen, no in-between screens.

I fixed all my issues by using the navigator service provided by @unexge, found in https://github.com/react-community/react-navigation/issues/1439.

**Comment by kelset** [comment]
> You guys are pointing to that PR in every single issue you close that is related to resetting the navigation stack or going back to a certain screen without seeing all the screens animate as the fix for it. It should be noted, that by using it, you're breaking other things.

What? That PR has been open for 5 days. And I've referenced it in two issues which are both **still open**.

So please, take that attitude somewhere else.

Moreover you seem to not understand that #2520 was not merged to enable you to use routeNames in goBack.

And, again, your issue lies inside another library:

> the author's forked version of react-navigation-addons

So go open an issue there.

**Comment by eballeste** [comment]
@kelset there is no attitude, please take a look at #1493 and tell me how it was closed? Could you maybe explain then the purpose of #2520 if I don't understand it? Why are you taking this so personal?

**Comment by 94cstyles** [comment]
@kelset You misinterpreted my meaning. 2520 is just fix animation-related issue. Did not fix `goBack` does not support routeName.
`react-native-addons` is just an experimental component. You can not use it.

**Comment by kelset** [comment]
> @kelset You misinterpreted my meaning. #2520 is just fix animation-related issue. Did not fix goBack does not support routeName.

Why are you telling me? I understand that, is @eballeste that opened this issue and is misinterpreting the PR.

My last comment was literally what you are saying

> #2520 was not merged to enable you to use routeNames in goBack.

**Comment by 94cstyles** [comment]
@kdenz sorry，@ Wrong
