### ISSUE TITLE
Undefined is not an object (evaluating navigation.state.routes) TabNavigator + redux

### ISSUE THREAD

**Issue by Tripwire999** [react-community/react-navigation#857]
Hi Guys,

I'm trying to implement the TabNavigator with Redux but I keep getting the error:
(evaluating 'navigation.state.routes')

I'm probably forgetting something in my implementation, so maybe someone can take a look? I've made a stackoverflow post:
[http://stackoverflow.com/questions/43087129/react-navigation-tabnavigator-with-redux-errors](url)

Thx!

**Comment by Tripwire999** [comment]
anyone?

**Comment by dominicrj23** [comment]
[Fixed URL](http://stackoverflow.com/questions/43087129/react-navigation-tabnavigator-with-redux-errors)

**Comment by dominicrj23** [comment]
`mapStateToProp` for `TabBarComponent` should have configuration 
```
const mapStateToProps = (state) => ({
    navigationState: state.tabBar
})
```

**Comment by Tripwire999** [comment]
Thanks! Feeling kinda stupid but it's working now :)

**Comment by ariona** [comment]
Hello @Tripwire999, @dominicrj23 , I kinda have the same issue here, i still get the save error.
Current configuration, what am i missing here?
```js
// export default MainScreenNavigator
const MainScreenNavigatorState = ({dispatch, navigationState}) => (
	<MainScreenNavigator
		navigation={
			addNavigationHelpers({
				dispatch: dispatch,
				state: navigationState,
			})
		}
	/>
)

const mapStateToProps = (state) => ({
    navigationState: state.tabBar
})

export default connect(mapStateToProps)(MainScreenNavigatorState);
```

**Comment by dominicrj23** [comment]
what is your store configuration. Make sure you are combining your reducer as tabBar. See posted code by @Tripwire999  at [stackOverflow](http://stackoverflow.com/questions/43087129/react-navigation-tabnavigator-with-redux-errors)

**Comment by ariona** [comment]
Hi @dominicrj23 thanks for heads up. Will try to learn the code.

**Comment by guoliang1206** [comment]
@grabbou  

excute this code in reducer:
```
const initialNavState = {
    index:0,
    routes: [
        { key: 'InitA', routeName: 'Login' },
        {
            key: 'InitB',
            routeName: 'Home',
            index:0,
            routes: [
                { key: 'InitC', routeName: 'TaskList', },
                { key: 'InitD', routeName: 'History', },
                { key: 'InitE', routeName: 'Setting', },
            ],
        },
    ],
};
```
`return  AppNavigator.router.getStateForAction(NavigationActions.reset({routeName:'Home'}), state);`

Error:
undefined is not an object (evaluating '_AppNavigator2.default.router.getStateForAction')

```
export const MainScreen  = TabNavigator ({
    TaskList:{ screen:TaskList },
    History:{ screen:History },
    Setting:{ screen:Setting },
});

export const AppNavigator = StackNavigator({
    Login:{ screen: LoginScreen },
    Home: { screen: MainScreen },
});


const AppWithNavigationState = ({ dispatch, nav }) => (
    <AppNavigator navigation={addNavigationHelpers({ dispatch, state: nav })} />
);

AppWithNavigationState.propTypes = {
    dispatch: PropTypes.func.isRequired,
    nav: PropTypes.object.isRequired,
};

const mapStateToProps = state => ({
    nav: state.nav,
});

export default connect(mapStateToProps)(AppWithNavigationState);

```

**Comment by guoliang1206** [comment]
in AppNavgator.js  
```
AppNavigator = { [Function: NavigationContainer]
  router: 
   { getComponentForState: [Function: getComponentForState],
     getComponentForRouteName: [Function: getComponentForRouteName],
     getStateForAction: [Function: getStateForAction],
     getPathAndParamsForState: [Function: getPathAndParamsForState],
     getActionForPathAndParams: [Function: getActionForPathAndParams],
     getScreenConfig: [Function] } }
```
but when in the Reducer.js 
```
AppNavigator = { [Function: Connect]
  WrappedComponent: 
   { [Function: AppWithNavigationState]
     propTypes: 
      { dispatch: [Function: bound checkType],
        nav: [Function: bound checkType] } },
  displayName: 'Connect(AppWithNavigationState)',
  childContextTypes: { storeSubscription: { [Function: bound checkType] isRequired: [Function: bound checkType] } },
  contextTypes: 
   { store: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     storeSubscription: { [Function: bound checkType] isRequired: [Function: bound checkType] } },
  propTypes: 
   { store: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     storeSubscription: { [Function: bound checkType] isRequired: [Function: bound checkType] } } }
```

**Comment by guoliang1206** [comment]
ok ,the answer is 
import { AppNavigator }  

not impport AppNavigator

**Comment by hnrqsss** [comment]
Check if the name of your nav reducer in comineReducers is the same in your mapStateToProps.
